//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CruiseChaserExporter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CruiseChaserExporter.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chara/action/mon_sp/m0361/hide/mon_sp001.tmb
        ///chara/action/mon_sp/m0361/hide/mon_sp001_hit.tmb
        ///chara/action/mon_sp/m0361/hide/mon_sp002.tmb
        ///chara/action/mon_sp/m0361/hide/mon_sp002_hit.tmb
        ///chara/action/mon_sp/m0361/hide/mon_sp003.tmb
        ///chara/action/mon_sp/m0361/hide/mon_sp012.tmb
        ///chara/action/mon_sp/m0361/mon_sp001.tmb
        ///chara/action/mon_sp/m0361/mon_sp001_hit.tmb
        ///chara/action/mon_sp/m0361/mon_sp002.tmb
        ///chara/action/mon_sp/m0361/mon_sp003.tmb
        ///chara/action/mon_sp/m0361/mon_sp004.tmb
        ///chara/action/mon_sp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string m0361 {
            get {
                return ResourceManager.GetString("m0361", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chara/action/mon_sp/m0489/hide/mon_sp001.tmb
        ///chara/action/mon_sp/m0489/hide/mon_sp001_hit.tmb
        ///chara/action/mon_sp/m0489/mon_sp001.tmb
        ///chara/action/mon_sp/m0489/mon_sp002.tmb
        ///chara/action/mon_sp/m0489/mon_sp003.tmb
        ///chara/action/mon_sp/m0489/mon_sp004.tmb
        ///chara/action/mon_sp/m0489/mon_sp004_hit.tmb
        ///chara/action/mon_sp/m0489/mon_sp005.tmb
        ///chara/action/mon_sp/m0489/mon_sp005_hit.tmb
        ///chara/action/mon_sp/m0489/mon_sp006.tmb
        ///chara/action/mon_sp/m0489/mon_sp006_hit.tmb
        ///chara/action/mon_sp/m0489/mon_sp007 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string m0489 {
            get {
                return ResourceManager.GetString("m0489", resourceCulture);
            }
        }
    }
}
